In [75]:
#  Uhlig's Exampl7.m
#  Two Country Stochastic Neoclassical Growth Model


import numpy as np


Z_bar_1   = 1
Z_bar_2   = 1
rho_1     = .36
rho_2     = .36
delta_1   = .025
delta_2   = .025
N_bar_1   = 1/2
N_bar_2   = 1/2
C_1_frac  = .5
betta     = 0.99
eta_1     = 1.0
eta_2     = 1.0

psi_1     = .95
psi_2     = .95

Sigma_EPS = .712
corr_12   = 0


R_bar_1   = 1.0/betta
R_bar_2   = 1.0/betta

YK_bar_1  = (R_bar_1 - 1 + delta_1)/rho_1
YK_bar_2  = (R_bar_2 - 1 + delta_2)/rho_2

K_bar_1 = N_bar_1 * ( Z_bar_1 / YK_bar_1 )**(1.0/(1-rho_1))
K_bar_2 = N_bar_2 * ( Z_bar_2 / YK_bar_2 )**(1.0/(1-rho_2))

Y_bar_1 = YK_bar_1 * K_bar_1
Y_bar_2 = YK_bar_2 * K_bar_2

X_bar_1 = delta_1 * K_bar_1
X_bar_2 = delta_2 * K_bar_2

Y_bar = Y_bar_1 + Y_bar_2
X_bar = X_bar_1 + X_bar_2

C_bar   = Y_bar - X_bar
C_bar_1 = C_1_frac * C_bar
C_bar_2 = (1-C_1_frac)*C_bar


VARNAMES = ['capital 1   ',
            'capital 2   ',
            'total cons. ',
            'total output',
            'tot.investm.',
            'consumption 1 ',
            'consumption 2 ',
            'output 1    ',
            'output 2    ',
            'investment 1',
            'investment 2',
            'return 1    ',
            'return 2    ',
            'technology 1',
            'technology 2',]


AA = np.vstack(([0, 0],  
                          [0, 0],
                          [0, 0],
                          [0, 0],
                          [0, 0], 
                          [0, 0],
                          [0, 0],
                          [-1, 0],
                          [0, -1],
                          [0, 0],
                          [0, 0]))


BB = np.vstack(([0, 0], 
                           [0, 0], 
                           [0, 0],  
                           [0, 0],  
                           [0, 0], 
                           [rho_1, 0], 
                           [0, rho_2],
                           [(1-delta_1),0],
                           [0,(1-delta_2)],
                           [-rho_1*YK_bar_1,0],
                           [0,-rho_2*YK_bar_2 ]))       

CC = np.vstack(([C_bar,-Y_bar, X_bar, 0,  0,    0,  0,    0,  0,  0,  0],
                           [0, 0,-X_bar, 0,  0, 0, 0, X_bar_1,X_bar_2, 0,0],
                           [0,-Y_bar, 0, 0, 0, Y_bar_1,Y_bar_2, 0, 0, 0, 0],
                           [-C_bar,0,0, C_bar_1,C_bar_2,0, 0, 0, 0, 0, 0],
                           [0, 0, 0,  eta_1,-eta_2, 0, 0, 0, 0, 0, 0],
                           [0, 0, 0, 0, 0,  -1, 0, 0, 0, 0, 0],
                           [0,0,0, 0, 0, 0, -1, 0, 0, 0, 0],
                           [0, 0, 0, 0, 0, 0, 0,delta_1,0, 0, 0],
                           [0, 0, 0, 0, 0, 0, 0, 0, delta_2, 0, 0],
                           [0, 0, 0, 0, 0, rho_1*YK_bar_1,0, 0, 0, -R_bar_1,0],
                           [0, 0, 0, 0, 0, 0, rho_2*YK_bar_2, 0, 0, 0,-R_bar_2 ]))

DD = np.vstack(([0,0],
                           [0,0],
                           [0,0],
                           [0,0],
                           [0,0],
                           [1,0],
                           [0,1],
                           [0,0],
                           [0,0],
                           [0,0],
                           [0,0]))

FF = np.vstack(([0, 0],
                          [0, 0]))

GG = np.vstack(([0, 0],
                            [0, 0]))

HH = np.vstack(([0, 0],
                           [0, 0]))

JJ = np.vstack(([0, 0, 0, -eta_1, 0, 0, 0, 0, 0, 1, 0],
                          [0, 0, 0, 0, -eta_2, 0, 0, 0, 0, 0, 1]))

KK = np.vstack(([0, 0, 0, eta_1, 0, 0, 0, 0, 0, 0, 0],
                           [0, 0, 0, 0, eta_2, 0, 0, 0, 0, 0, 0]))

LL = np.vstack(([0, 0],
                          [0, 0]))

MM = np.vstack(([0, 0],
                            [0, 0]))


NN = np.vstack(([psi_1, 0],
                           [0, psi_2]))

Sigma = [ Sigma_EPS**2]*np.vstack(([1, corr_12],[corr_12, 1]))

Sigma_EPS = Sigma


%run uhlig_solver_abrevated.ipynb




eVals =  [-7.0851e+12+0.j  1.0464e+00+0.j  9.6528e-01+0.j  5.6478e-14+0.j]
eVals shape = (4,)
 
eVecs =  [[ 0.7071  0.5112 -0.4911  0.    ]
 [-0.7071  0.5112 -0.4911 -0.    ]
 [-0.      0.4885 -0.5088  0.7071]
 [ 0.      0.4885 -0.5088 -0.7071]]
eVecs shape = (4, 4)
 
eVecs rank = 4
m_states =  2
rank of eVecs should be = > m_states 
 
Xi_sortabs =  [5.6478e-14 9.6528e-01 1.0464e+00 7.0851e+12]
Xi_sortabs shape = (4,)
 
Xi_sortindex =  [3 2 1 0]
Xi_sortindex shape = (4,)
 
Xi_sortVec =  [[ 0.     -0.4911  0.5112  0.7071]
 [-0.     -0.4911  0.5112 -0.7071]
 [ 0.7071 -0.5088  0.4885 -0.    ]
 [-0.7071 -0.5088  0.4885  0.    ]]
Xi_sortVec shape = (4, 4)
 
Xi_sortval =  [ 5.6478e-14+0.j  9.6528e-01+0.j  1.0464e+00+0.j -7.0851e+12+0.j]
Xi_sortval = (4,)
 
Xi_select =  [0 1]
Xi_select = (2,)
 
 
Xi_sortval[Xi_select].imag =  [0. 0.]
Does Xi_sortval[Xi_select] have complex numbers?
Go check parameterization.
Nevertheless, I am proceeding as is.
  
Xi_sortval[Xi_select].real =  [0.     0.9653]

In [84]:
#   This is filename:  Uhlig_impulse_resp_all

#  Specify Horizon below


import matplotlib.pyplot as pl


np.set_printoptions(precision=4, suppress=True)


Horizon = 12


m_states = QQ.shape[0]
k_exog = QQ.shape[1]
n_endog = SS.shape[0]
#k_exog = SS.shape[1]
#print('Horizon = ', Horizon)
#print('m_states = ', m_states)
#print('n_endog = ', n_endog)
#print('k_exog = ', k_exog)


VN_temp= np.matrix(VARNAMES)
VARNAMES = VN_temp.reshape((m_states+k_exog+n_endog),1)
temp_named = np.vstack((['Period'],VARNAMES))

Period_list = np.matrix(range(0,Horizon+1)).reshape(1, Horizon+1)
#Resp_mat = Period_list


shock_counter = 0
time_counter = 0
#print('shock_counter = ', shock_counter)
#print('time_counter = ', time_counter)


for shock_counter in range(k_exog):
    #print('shock_counter = ', shock_counter)
    Response =  np.zeros((m_states+n_endog+k_exog)*Horizon).reshape(m_states+n_endog+k_exog, Horizon)
    Response = np.array(Response)
    #print('Response = ', Response)
    Response[m_states+n_endog+shock_counter,0] = 1
    #print('Response = ', Response)
                    
    II_Lag_01 = np.hstack(((PP, np.zeros(m_states*n_endog).reshape(m_states, n_endog), np.zeros(m_states*k_exog).reshape(m_states, k_exog))))
    II_Lag_02 = np.hstack(((RR, np.zeros(n_endog*n_endog).reshape(n_endog, n_endog), np.zeros(n_endog*k_exog).reshape(n_endog, k_exog))))
    II_Lag_03 = np.hstack(((np.zeros(k_exog*(m_states+n_endog)).reshape(k_exog, (m_states+n_endog)), NN)))
    II_Lag = np.vstack((II_Lag_01, II_Lag_02, II_Lag_03))
    #print('II_Lag = ', II_Lag)
                    
    II_Contemp_01 = np.eye(m_states+n_endog+k_exog)
    II_Contemp_02 = np.hstack((np.zeros(m_states*(m_states+n_endog)).reshape(m_states, (m_states+n_endog)), QQ))
    II_Contemp_03 = np.hstack((np.zeros(n_endog*(m_states+n_endog)).reshape(n_endog, (m_states+n_endog)), SS))
    II_Contemp_04 = np.hstack((np.zeros(k_exog*(m_states+n_endog)).reshape(k_exog, (m_states+n_endog)), np.zeros(k_exog*k_exog).reshape(k_exog, k_exog)))
    II_Contemp = II_Contemp_01+ np.vstack((II_Contemp_02, II_Contemp_03, II_Contemp_04))
    #print('II_Contemp = ', II_Contemp)
                    
    Response_0 = np.array(Response[:,0]).reshape((m_states+n_endog+k_exog),1)
    #print('Response_0 = ', Response_0)
    #print('Response_0 shape = ', Response_0.shape)
    
    Response_1 = dot(II_Contemp, Response_0).reshape((m_states+n_endog+k_exog),1)
    #print('Response_1 = ', Response_1)
    #print('Response_1 shape = ', Response_1.shape)
    
    Response = Response_1
                    
    for time_counter in range(0, Horizon):
        # print('time_counter = ', time_counter)
        Resp_col = dot(dot(II_Contemp, II_Lag), Response[:,time_counter -1])
        Response = np.hstack((Response, Resp_col))
        # print('time_counter = ', time_counter)
        # print(Response)
        
    Resp_mat = np.vstack((Period_list, Response))
##########   

Resp_mat_collect = Resp_mat
    
    if shock_counter == 1:
        Resp_mat_collect = Resp_mat
    else:
        Resp_mat_collect = np.vstack((Resp_mat_collect,Resp_mat))

        
print('Resp_mat = ',Resp_mat)
    

    
for shock_counter in range(1,k_exog):    
    
    if shock_counter == 1:
        VAR_NAMES = temp_named
    else:
        VAR_NAMES = np.vstack((VAR_NAMES,temp_named))
    
Resp_mat_named = np.hstack((VAR_NAMES, Resp_mat))     
print('Resp_mat_named = ', Resp_mat_named)


print('  ')    
print('Done. You have the matrices "Resp_mat" and "Resp_mat_named" ')
print('which contains impulse reponses to 1% innovations')
print('for all exogenous stochastic processes in the model.')
print('If you want, you can download this into an excel file or plot.')
print('  ')   



Resp_mat =  [[ 0.      1.      2.      3.      4.      5.      6.      7.      8.
   9.     10.     11.     12.    ]
 [ 0.0136  0.0261  0.0261  0.0375  0.0375  0.0479  0.0479  0.0574  0.0574
   0.066   0.066   0.0737  0.0737]
 [ 0.0136  0.0261  0.0261  0.0375  0.0375  0.0479  0.0479  0.0574  0.0574
   0.066   0.066   0.0737  0.0737]
 [ 0.1748  0.1745  0.1745  0.1739  0.1739  0.1731  0.1731  0.172   0.172
   0.1708  0.1708  0.1693  0.1693]
 [ 0.27    0.2614  0.2614  0.2531  0.2531  0.245   0.245   0.2372  0.2372
   0.2296  0.2296  0.2222  0.2222]
 [ 0.5459  0.5133  0.5133  0.4825  0.4825  0.4534  0.4534  0.426   0.426
   0.4001  0.4001  0.3756  0.3756]
 [ 0.1748  0.1745  0.1745  0.1739  0.1739  0.1731  0.1731  0.172   0.172
   0.1708  0.1708  0.1693  0.1693]
 [ 0.1748  0.1745  0.1745  0.1739  0.1739  0.1731  0.1731  0.172   0.172
   0.1708  0.1708  0.1693  0.1693]
 [ 0.      0.0049  0.0049  0.0094  0.0094  0.0135  0.0135  0.0173  0.0173
   0.0207  0.0207  0.0237  0.0237]
 [ 0.      0.00

In [81]:
print(shock_counter)

0
