In [1]:
#  Uhlig's Exampl6.m
#  A Small Open Economy Stochastic Neoclassical 
#  Growth Model with Adjustment Costs for Capital

import numpy as np

Z_bar = 1
NPV_frac = 0.5
rho = 0.36
delta = 0.025
R_bar = 1.01
eta = 1.0
theta = 0.8
psi_z = 0.95
sigma_z = 0.712
psi_r = 0.95
sigma_r = 1.0
corr_z_r = 0

betta = 1.0/R_bar
XK_bar = ((1+delta)**theta - 1)**(1.0/theta)
FK_omt = (1+delta)**(1-theta)
FX_omt = FK_omt/XK_bar**(1-theta)
YK_bar = (R_bar - FK_omt + delta)/(rho*FX_omt)
K_bar = (Z_bar/YK_bar)**(1.0/(1-rho))
Y_bar = Z_bar*K_bar**rho
X_bar = XK_bar*K_bar
F_bar = (1+delta)*K_bar
A_bar = NPV_frac * (Y_bar/(R_bar - 1))
C_bar = Y_bar - X_bar + (R_bar - 1)*A_bar

VARNAMES = ['capital ',
                         'assets ',
                         'consumption ',
                         'investment ',
                         'output ',
                         'intermediate capital ',
                         'technology ',
                         'return ' ]

AA = np.vstack(([ 0, -A_bar],
                           [0, 0], 
                           [-1, 0],    
                           [0, 0]))

BB = np.vstack(([0, R_bar*A_bar],
                           [rho, 0],
                           [-delta, 0],       
                           [K_bar**theta, 0]))

CC = np.vstack(([ -C_bar, -X_bar, Y_bar, 0],
                           [0, 0, -1, 0],
                           [0, 0, 0,(1+delta)],
                           [0, X_bar**theta, 0, (-F_bar**theta) ]))


DD = np.vstack(([0,R_bar*A_bar],
                           [1,0],
                           [0,0],          
                           [0,0]))

FF = np.vstack(([0,0], 
                          [0,0]))

GG = np.vstack(([0, 0],
                           [(-((rho/R_bar)*YK_bar*FX_omt + (1-theta)*FK_omt/R_bar) ),0]))

HH = np.vstack(([0,0],
                           [0,0]))

JJ = np.vstack(([-eta, 0, 0, 0],     
                          [-eta,(1-theta)*(FK_omt-delta)/R_bar,(rho/R_bar)*YK_bar*FX_omt,delta*(1-theta)/R_bar]))

KK = np.vstack(([eta, 0, 0, 0],
                           [eta,theta-1,0,1-theta]))

LL = np.vstack(([0,1],
                          [0,0]))

MM = np.vstack(([0,0],
                            [0,0]))

NN = np.vstack(([psi_z, 0],
                           [0, psi_r ]))

Sigma = np.vstack(([sigma_z**2, corr_z_r*sigma_z*sigma_r], 
                                [corr_z_r*sigma_z*sigma_r, sigma_r**2]))

Sigma_EPS = Sigma


%run Uhlig_solver_QZ.ipynb



qzdiv(): Inputs unchanged!
Done. You have the matrices PP QQ  RR  SS  WW.


In [2]:
print('PP')
print(PP.shape)
print(PP)
print(' ')
print('RR')
print(RR.shape)
print(RR)
print(' ')
print('QQ')
print(QQ.shape)
print(QQ)
print(' ')
print('SS')
print(SS.shape)
print(SS)
print(' ')
print('Delta_up = ', Delta_up)
print(' ')
print('Xi_up = ', Xi_up)
print(' ')
print('UUU = ', UUU)
print(' ')
print('VVV = ', VVV)

PP
(2, 2)
[[9.612e-01 2.543e-14]
 [9.288e-03 1.000e+00]]
 
RR
(4, 2)
[[ 9.510e-02  3.969e-01]
 [-9.333e-01  1.268e-12]
 [ 3.600e-01  9.755e-17]
 [ 9.622e-01  2.478e-14]]
 
QQ
(2, 2)
[[ 0.029 -0.974]
 [ 0.01   1.474]]
 
SS
(4, 2)
[[ 1.323e-01 -9.152e+00]
 [ 1.445e+00 -4.858e+01]
 [ 1.000e+00  0.000e+00]
 [ 2.827e-02 -9.502e-01]]
 
Delta_up =  [[-6.566e+00+0.j  3.024e+01+0.j  6.815e+00+0.j -3.027e+01+0.j]
 [ 0.000e+00+0.j -2.906e+01+0.j -3.023e-01+0.j  2.903e+01+0.j]
 [ 0.000e+00+0.j -9.148e-15+0.j  1.425e+00+0.j -1.072e-02+0.j]
 [ 0.000e+00+0.j  0.000e+00+0.j  0.000e+00+0.j  1.414e+00+0.j]]
 
Xi_up =  [[-6.311e+00+0.j  3.018e+01+0.j  2.035e+01+0.j -9.142e+01+0.j]
 [ 1.594e-18+0.j -2.906e+01+0.j -3.107e-01+0.j  8.773e+01+0.j]
 [-1.379e-17+0.j -8.667e-15+0.j  1.497e+00+0.j -2.473e-02+0.j]
 [ 0.000e+00+0.j  0.000e+00+0.j  0.000e+00+0.j  1.428e+00+0.j]]
 
UUU =  [[-1.547e-13+0.j  9.940e-01+0.j  1.068e-01+0.j -2.559e-02+0.j]
 [-9.931e-01+0.j -1.261e-02+0.j  1.053e-01+0.j -5.026e-02+0.j]
 [-1