In [1]:
#  Uhlig's Exampl7.m
#  Two Country Stochastic Neoclassical Growth Model


import numpy as np


Z_bar_1   = 1
Z_bar_2   = 1
rho_1     = 0.36
rho_2     = 0.36
delta_1   = 0.025
delta_2   = 0.025
N_bar_1   = 1/2
N_bar_2   = 1/2
C_1_frac  = 0.5
betta     = 0.99
eta_1     = 1.0
eta_2     = 1.0

psi_1     = 0.95
psi_2     = 0.95

sigma_sigma = 0.712
corr_12   = 0


R_bar_1   = 1.0/betta
R_bar_2   = 1.0/betta

YK_bar_1  = (R_bar_1 - 1 + delta_1)/rho_1
YK_bar_2  = (R_bar_2 - 1 + delta_2)/rho_2

K_bar_1 = N_bar_1 * ( Z_bar_1 / YK_bar_1 )**(1.0/(1-rho_1))
K_bar_2 = N_bar_2 * ( Z_bar_2 / YK_bar_2 )**(1.0/(1-rho_2))

Y_bar_1 = YK_bar_1 * K_bar_1
Y_bar_2 = YK_bar_2 * K_bar_2

X_bar_1 = delta_1 * K_bar_1
X_bar_2 = delta_2 * K_bar_2

Y_bar = Y_bar_1 + Y_bar_2
X_bar = X_bar_1 + X_bar_2

C_bar   = Y_bar - X_bar
C_bar_1 = C_1_frac * C_bar
C_bar_2 = (1-C_1_frac)*C_bar


VARNAMES = ['capital 1   ',
            'capital 2   ',
            'total cons. ',
            'total output',
            'tot.investm.',
            'consumption 1 ',
            'consumption 2 ',
            'output 1    ',
            'output 2    ',
            'investment 1',
            'investment 2',
            'return 1    ',
            'return 2    ',
            'technology 1',
            'technology 2',]


AA = np.vstack(([0, 0],  
                          [0, 0],
                          [0, 0],
                          [0, 0],
                          [0, 0], 
                          [0, 0],
                          [0, 0],
                          [-1, 0],
                          [0, -1],
                          [0, 0],
                          [0, 0]))


BB = np.vstack(([0, 0], 
                           [0, 0], 
                           [0, 0],  
                           [0, 0],  
                           [0, 0], 
                           [rho_1, 0], 
                           [0, rho_2],
                           [(1-delta_1),0],
                           [0,(1-delta_2)],
                           [-rho_1*YK_bar_1,0],
                           [0,-rho_2*YK_bar_2 ]))       

CC = np.vstack(([C_bar,-Y_bar, X_bar, 0,  0,    0,  0,    0,  0,  0,  0],
                           [0, 0,-X_bar, 0,  0, 0, 0, X_bar_1,X_bar_2, 0,0],
                           [0,-Y_bar, 0, 0, 0, Y_bar_1,Y_bar_2, 0, 0, 0, 0],
                           [-C_bar,0,0, C_bar_1,C_bar_2,0, 0, 0, 0, 0, 0],
                           [0, 0, 0,  eta_1,-eta_2, 0, 0, 0, 0, 0, 0],
                           [0, 0, 0, 0, 0,  -1, 0, 0, 0, 0, 0],
                           [0,0,0, 0, 0, 0, -1, 0, 0, 0, 0],
                           [0, 0, 0, 0, 0, 0, 0,delta_1,0, 0, 0],
                           [0, 0, 0, 0, 0, 0, 0, 0, delta_2, 0, 0],
                           [0, 0, 0, 0, 0, rho_1*YK_bar_1,0, 0, 0, -R_bar_1,0],
                           [0, 0, 0, 0, 0, 0, rho_2*YK_bar_2, 0, 0, 0,-R_bar_2 ]))

DD = np.vstack(([0,0],
                           [0,0],
                           [0,0],
                           [0,0],
                           [0,0],
                           [1,0],
                           [0,1],
                           [0,0],
                           [0,0],
                           [0,0],
                           [0,0]))

FF = np.vstack(([0, 0],
                          [0, 0]))

GG = np.vstack(([0, 0],
                            [0, 0]))

HH = np.vstack(([0, 0],
                           [0, 0]))

JJ = np.vstack(([0, 0, 0, -eta_1, 0, 0, 0, 0, 0, 1, 0],
                          [0, 0, 0, 0, -eta_2, 0, 0, 0, 0, 0, 1]))

KK = np.vstack(([0, 0, 0, eta_1, 0, 0, 0, 0, 0, 0, 0],
                           [0, 0, 0, 0, eta_2, 0, 0, 0, 0, 0, 0]))

LL = np.vstack(([0, 0],
                          [0, 0]))

MM = np.vstack(([0, 0],
                            [0, 0]))


NN = np.vstack(([psi_1, 0],
                           [0, psi_2]))

Sigma = [sigma_sigma**2]*np.vstack(([1, corr_12],[corr_12, 1]))

Sigma_EPS = Sigma


%run uhlig_solver_QZ.ipynb



qzdiv(): Inputs unchanged!
Done. You have the matrices PP QQ  RR  SS  WW.


In [2]:
print('PP')
print(PP.shape)
print(PP)
print(' ')
print('RR')
print(RR.shape)
print(RR)
print(' ')
print('QQ')
print(QQ.shape)
print(QQ)
print(' ')
print('SS')
print(SS.shape)
print(SS)
print(' ')
print('Delta_up = ', Delta_up)
print(' ')
print('Xi_up = ', Xi_up)
print(' ')
print('UUU = ', UUU)
print(' ')
print('VVV = ', VVV)

PP
(2, 2)
[[0.483 0.483]
 [0.483 0.483]]
 
RR
(11, 2)
[[ 3.091e-01  3.091e-01]
 [ 1.800e-01  1.800e-01]
 [-1.945e-01 -1.945e-01]
 [ 3.091e-01  3.091e-01]
 [ 3.091e-01  3.091e-01]
 [ 3.600e-01  6.538e-16]
 [ 1.094e-15  3.600e-01]
 [-1.969e+01  1.931e+01]
 [ 1.931e+01 -1.969e+01]
 [-2.224e-02 -2.336e-15]
 [-1.912e-15 -2.224e-02]]
 
QQ
(2, 2)
[[ 0.78  -0.705]
 [-0.705  0.78 ]]
 
SS
(11, 2)
[[  0.153   0.153]
 [  0.5     0.5  ]
 [  1.507   1.507]
 [  0.153   0.153]
 [  0.153   0.153]
 [  1.      0.   ]
 [  0.      1.   ]
 [ 31.195 -28.18 ]
 [-28.18   31.195]
 [  0.035   0.   ]
 [  0.      0.035]]
 
Delta_up =  [[ 1.000e+00-4.406e-03j  2.008e-14+1.308e-14j -3.234e-15+2.419e-14j
  -1.433e-14+2.429e-14j]
 [ 0.000e+00+0.000e+00j  9.606e+00-1.648e-13j  3.880e+00+9.047e+00j
  -1.846e-13-3.640e-13j]
 [ 0.000e+00+0.000e+00j  0.000e+00+0.000e+00j  1.436e+00+2.047e-14j
  -1.590e-13+1.036e-14j]
 [ 0.000e+00+0.000e+00j  0.000e+00+0.000e+00j  0.000e+00+0.000e+00j
  -1.884e-15+2.164e-20j]]
 
Xi_up =  [[